version: '2.0'
services:
  dynamodb:
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      volumes:
        - "./docker/dynamodb:/home/dynamodblocal/data"
  warehouse:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5555:5555
    command: -p 5555
  # meltano:
  #   image: meltano/meltano
  #   restart: always
  #   environment:
      